version: '3.8'
services:
  server:
    container_name: misadrawings_server
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: unless-stopped